name: tomato_library
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
